language: generic
dist: trusty

services:
- docker

env:
  global:
  - AWS_REGION='eu-west-1'
  - TF_VAR_region=${AWS_REGION}
  - TF_WARN_OUTPUT_ERRORS=1

before_script:
- export TERRAFORM_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
- curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
- unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
- mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
- terraform version

script:
- echo 'script'
- terraform init
- terraform fmt -check=true
- terraform validate
- |
  for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
  cd $example
  terraform init
  terraform fmt -check=true
  terraform validate
  cd -
  done
- terraform version

notifications:
  email:
    recipients:
    - rekcah78@gmail.com
    on_success: change
    on_failure: change
